version: '3.4'

services:
  gosmartvalue.web:
    image: ${DOCKER_REGISTRY-}gosmartvalue-api
    build:
      context: .
      dockerfile: GoSmartValue.Web/Dockerfile
        
  gosmartvalue.angular.app:
    image: ${DOCKER_REGISTRY-}gosmartvalue-web
    build:
      context: .
      dockerfile: GoSmartValue.Web/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./GoSmartValue.Web/ClientApp:/app